# Updates credly badges via @pemtajo's actions
name: 📛 Update Credly badge

on:
  workflow_dispatch: # Manual dispatch
  schedule:
    # Runs at 0am UTC every day
    - cron: "0 0 1/10 * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          COMMIT_MESSAGE: ":badge: Updates New Badges"
          CREDLY_SORT: POPULAR
