# Updates credly badges via @pemtajo's actions
name: 📛 Update Credly badge

on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: "0 17 1/10 * *" # Runs at 24:00 WIB on the 1, 11, 21, and 31st of every month
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          COMMIT_MESSAGE: ":sparkles: Updates New Badges"
          CREDLY_USER: "dicky-rahma-hermawan"
          CREDLY_SORT: POPULAR
